service: face-recognition

provider:
  name: aws
  region: ap-southeast-1
  runtime: go1.x
  stage: v1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rekognition:DetectFaces
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: "arn:aws:s3:::face-recognition-authenticated/*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  main:
    handler: bin/main
    events:
      - s3:
          bucket: face-recognition-authenticated
          event: s3:ObjectCreated:*
