service: face-recognition-search-face

provider:
  name: aws
  region: ap-southeast-1
  runtime: go1.x
  stage: v1
  iam:
    role:
      name: face-recognition-search-face-role
      statements:
        - Effect: Allow
          Action:
            - rekognition:SearchFacesByImage
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: "arn:aws:s3:::transaction-bbeetech/*"
        - Effect: Allow
          Action:
            - dynamodb:GetItem
          Resource:
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/face-recognition-authenticated*
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/face-recognition-authenticated*/index/*
package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  main:
    handler: bin/main
    events:
      - s3:
          bucket: transaction-bbeetech
          event: s3:ObjectCreated:*

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: face-recognition-authenticated
        AttributeDefinitions:
          - AttributeName: faceId
            AttributeType: S
          - AttributeName: customerId
            AttributeType: S
        KeySchema:
          - AttributeName: faceId
            KeyType: HASH
          - AttributeName: customerId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
