service: go-face-recognition-search-face

provider:
  name: aws
  region: ap-southeast-1
  runtime: go1.x
  stage: v1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - rekognition:IndexFaces
          Resource: "*"
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: "arn:aws:s3:::face-recognition-authenticated/*"
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource:
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/face-recognition-authenticated*
            - arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/face-recognition-authenticated*/index/*
package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  main:
    handler: bin/main
    events:
      - s3:
          bucket: face-recognition-authenticated
          event: s3:ObjectCreated:*
